// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfceuxducvosduupojie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmY2V1eGR1Y3Zvc2R1dXBvamllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzA4NjcsImV4cCI6MjA2MzE0Njg2N30.80c-9yX9kP7RWRgSXgwib-Fuw6x1E5ImhkoZrWvfmCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);